export const fonts = {
  mark: "'Mark Pro', sans-serif",
  roboto: "'Roboto', sans-serif",
  poppins: "'Poppins', sans-serif",
  "0.5rem": "0.5rem",
  "1rem": "1rem !important",
  "1.1rem": "1.1rem !important",
  "1.2rem": "1.2rem !important",
  "1.3rem": "1.3rem !important",
  "1.4rem": "1.4rem !important",
  "1.5rem": "1.5rem !important",
  "2rem": "2rem !important",
  "3rem": "3rem !important",
  "4rem": "4rem !important",
  "5rem": "5rem !important",
  "30px": "30px",
  ".813em": ".813em",
};
